services:  
  client:
    build: 
      context: ./blogs-front
      dockerfile: Dockerfile     
    ports:
      - 8080:80
   
  server:
    build:
      context: ./blogs-back
      dockerfile: Dockerfile 
    container_name: blogs-backend
    ports: 
      - 3001:3001   