version: '3.8'

services:
  
  database:
    image: mongo
    restart: always
    container_name: mongo_database
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo_data:/data/db

  redis:
    image: redis
    container_name: cache   
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes: 
      - redis_data:/data


  server:
    image: express-server
    container_name: backend-server
    build: .
    ports:
      - 3000:3000   
   
volumes:
  mongo_data:
  redis_data:



