version: '3.9'

services:

  server:
    build:
      context: .
      dockerfile: dev.Dockerfile 
    container_name: backend-server-dev   
    ports:
      - 3001:3001   
    environment: 
      - REDIS_URL=redis://cache:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo_database:27017/the_database

  database:
    image: mongo
    restart: always
    container_name: mongo_database
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo_data:/data/db

  redis:
    image: redis
    container_name: cache   
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis_data:/data  

volumes:
  mongo_data:
  redis_data:
